import fs from "fs";
import path from "path";

// How the business wants its negotiation agent to sound & sell.
export interface AgentPersona {
  tone?: string; // e.g. "friendly", "cheeky", "formal", "premium"
  languageStyle?: string; // e.g. "standard", "singlish", "concise", "storytelling"
  dietary?: string[]; // e.g. ["halal", "vegetarian-friendly"]
  languages?: string[]; // greeting languages e.g. ["English", "Malay", "Mandarin"]
  emphasis?: string[]; // selling points to push, e.g. ["value", "quality", "speed"]
  tagline?: string; // custom brand line the agent can use
  notes?: string; // free-form voice instructions from the owner
}

// A single product / menu item in the business's catalog.
export interface CatalogItem {
  name: string;
  price?: number;
  description?: string;
  tags?: string[];
}

export interface Business {
  id: string;
  name: string;
  knowledge: string;
  isReady: boolean;
  menuUrl?: string;
  foodpandaCode?: string;
  location?: string;
  isAutoGenerated?: boolean;
  persona?: AgentPersona;
  catalog?: CatalogItem[];
  importSource?: string;
  conversationHistory: { role: "user" | "assistant"; content: string }[];
}

const DATA_PATH =
  process.env.VERCEL === "1"
    ? path.join("/tmp", "agentbid-businesses.json")
    : path.join(process.cwd(), "data", "businesses.json");

function ensureDataDir() {
  const dir = path.dirname(DATA_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function loadAll(): Map<string, Business> {
  ensureDataDir();
  if (!fs.existsSync(DATA_PATH)) return new Map();
  const raw = JSON.parse(fs.readFileSync(DATA_PATH, "utf-8")) as Business[];
  return new Map(raw.map((b) => [b.id, b]));
}

function saveAll(businesses: Map<string, Business>) {
  ensureDataDir();
  fs.writeFileSync(DATA_PATH, JSON.stringify(Array.from(businesses.values()), null, 2));
}

export function getAllBusinesses(): Business[] {
  return Array.from(loadAll().values()).filter((b) => b.isReady);
}

export function getBusiness(id: string): Business | undefined {
  return loadAll().get(id);
}

export function upsertBusiness(business: Business): void {
  const all = loadAll();
  all.set(business.id, business);
  saveAll(all);
}
