import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { openai } from "@/app/lib/openai";
import {
  Business,
  getAllBusinesses,
  upsertBusiness,
} from "@/app/lib/store";
import { searchReviews, searchSupplierInfo } from "@/app/lib/exa";
import { personaToPrompt } from "@/app/lib/persona";

// ---- Incoming shape (the JSON your friend sends) ----
interface SupplierOption {
  id?: string;
  vendor: string;
  item: string;
  description?: string;
  price: number;
  currency?: string;
  link?: string;
  order_url?: string;
  why_pick?: string;
  metadata?: Record<string, unknown>;
}

interface NegotiateRequest {
  itemDescription: string; // what the user is looking for
  price?: number; // user's budget / target price (optional)
  options: { options: SupplierOption[] } | SupplierOption[];
}

// ---- Output shape ----
interface NegotiatedResult {
  supplier_name: string;
  supplier_location: string;
  total_cost: number;
  currency: string;
  item_name: string;
  item_description: string;
  // helpful extras
  score: number;
  within_budget: boolean;
  agent_source: "registered" | "researched";
  reasoning: string;
  order_url?: string;
}

// Normalise a name for fuzzy matching against registered agents.
function normalize(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

// Match a friend-supplied vendor name to an existing registered agent.
function findExistingAgent(vendor: string, businesses: Business[]): Business | undefined {
  const v = normalize(vendor);
  return businesses.find((b) => {
    const n = normalize(b.name);
    return n.length > 0 && (v.includes(n) || n.includes(v));
  });
}

// Auto-research an unknown vendor and build + persist a negotiation agent for it.
async function autoOnboardSupplier(
  vendor: string,
  options: SupplierOption[]
): Promise<Business> {
  const webInfo = await searchSupplierInfo(vendor);

  // Seed context from the friend's options (already-known items/prices/hints).
  const seed = options
    .map(
      (o) =>
        `- ${o.item} (${o.currency || "SGD"} ${o.price}): ${o.description || ""}${
          o.why_pick ? ` | hint: ${o.why_pick}` : ""
        }`
    )
    .join("\n");

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content: `You are onboarding a NEW supplier "${vendor}" that has not registered on our platform. Using the web research and the known menu items below, build a negotiation profile.

Return STRICT JSON:
{
  "location": "best-known physical location / area (city + area). Empty string if truly unknown.",
  "knowledge": "a thorough paragraph describing the vendor: cuisine/category, signature items, price positioning, values, ambiance, and what makes them stand out — grounded ONLY in the provided info. Do not invent facts."
}`,
      },
      {
        role: "user",
        content: `Vendor: ${vendor}\n\nKnown menu items (from partner feed):\n${seed}\n\nWeb research:\n${
          webInfo || "(no web results found)"
        }`,
      },
    ],
  });

  let location = "";
  let knowledge = "";
  try {
    const parsed = JSON.parse(completion.choices[0].message.content || "{}");
    location = (parsed.location || "").trim();
    knowledge = (parsed.knowledge || "").trim();
  } catch {
    knowledge = completion.choices[0].message.content || "";
  }

  const business: Business = {
    id: randomUUID(),
    name: vendor,
    knowledge: knowledge || `Auto-generated profile for ${vendor}.`,
    isReady: true,
    isAutoGenerated: true,
    location,
    conversationHistory: [
      {
        role: "assistant",
        content: `[AUTO-ONBOARDED]\nLocation: ${location}\n\n${knowledge}`,
      },
    ],
  };

  upsertBusiness(business);
  return business;
}

// Each vendor agent pitches its best in-budget item for the request.
async function vendorPitch(
  business: Business,
  options: SupplierOption[],
  itemDescription: string,
  budget: number | undefined,
  reviews: string
): Promise<string> {
  const menu = options
    .map(
      (o) =>
        `- ${o.item} (${o.currency || "SGD"} ${o.price}): ${o.description || ""}`
    )
    .join("\n");

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `You are the negotiation agent for "${business.name}".

YOUR KNOWLEDGE:
${business.knowledge}
${business.location ? `\nLOCATION: ${business.location}` : ""}

YOUR ACTUAL AVAILABLE ITEMS (you may ONLY reference these — do not invent items):
${menu}

WEB REVIEWS:
${reviews}

The customer wants: "${itemDescription}"${
          budget ? `\nBudget: SGD ${budget} (do not push items over budget as the main pick).` : ""
        }

Make a tight, specific pitch for which of YOUR listed items best matches the request and budget. Reference real item names and prices. Be persuasive but truthful — never claim an item you do not have. 1-2 short paragraphs.${personaToPrompt(
          business.persona
        )}`,
      },
      { role: "user", content: `Pitch your best option for: ${itemDescription}` },
    ],
  });
  return response.choices[0].message.content || "";
}

// The buyer's skeptical agent challenges every vendor after the pitches.
async function buyerChallenge(
  itemDescription: string,
  budget: number | undefined,
  pitched: { business: Business; pitch: string; reviews: string }[]
): Promise<string> {
  const pitchSummary = pitched
    .map((p) => `## ${p.business.name}\n${p.pitch}`)
    .join("\n\n---\n\n");
  const reviewSummary = pitched
    .map((p) => `## ${p.business.name} (web reviews)\n${p.reviews}`)
    .join("\n\n");

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `You are the buyer's skeptical negotiation agent. The buyer wants "${itemDescription}"${
          budget ? ` within a budget of SGD ${budget}` : ""
        }. You've heard each vendor's pitch and seen real web reviews. Challenge EACH vendor with 1-2 pointed questions or objections — about price/value, fit to the request, portion/quality, or anything reviews contradict. Be adversarial; you are protecting the buyer's interests.`,
      },
      {
        role: "user",
        content: `Pitches:\n${pitchSummary}\n\nReal web reviews:\n${reviewSummary}\n\nChallenge each vendor.`,
      },
    ],
  });
  return response.choices[0].message.content || "";
}

// Each vendor agent responds to the buyer agent's challenge.
async function vendorCounter(
  business: Business,
  options: SupplierOption[],
  challenge: string,
  reviews: string
): Promise<string> {
  const menu = options
    .map(
      (o) =>
        `- ${o.item} (${o.currency || "SGD"} ${o.price}): ${o.description || ""}`
    )
    .join("\n");

  const response = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `You are the negotiation agent for "${business.name}". The buyer's agent has raised challenges and objections. Respond to the points aimed at you: defend your offering honestly, acknowledge valid criticism but spin it positively, and reference real prices.

YOU MAY ONLY REFERENCE THESE ITEMS (never invent items):
${menu}

WEB REVIEWS ABOUT YOU:
${reviews}${personaToPrompt(business.persona)}`,
      },
      { role: "user", content: challenge },
    ],
  });
  return response.choices[0].message.content || "";
}

export async function POST(req: NextRequest) {
  let body: NegotiateRequest;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { itemDescription, price } = body;
  const rawOptions = Array.isArray(body.options)
    ? body.options
    : body.options?.options;

  if (!itemDescription || !Array.isArray(rawOptions) || rawOptions.length === 0) {
    return NextResponse.json(
      { error: "Require 'itemDescription' and a non-empty 'options' array." },
      { status: 400 }
    );
  }

  // Group friend-supplied options by vendor.
  const byVendor = new Map<string, SupplierOption[]>();
  for (const o of rawOptions) {
    if (!o?.vendor || !o?.item || typeof o.price !== "number") continue;
    const list = byVendor.get(o.vendor) || [];
    list.push(o);
    byVendor.set(o.vendor, list);
  }
  if (byVendor.size === 0) {
    return NextResponse.json(
      { error: "No valid options (each needs vendor, item, price)." },
      { status: 400 }
    );
  }

  const registered = getAllBusinesses();

  // Resolve every vendor to an agent — reuse a registered one, or auto-onboard.
  const resolved = await Promise.all(
    Array.from(byVendor.entries()).map(async ([vendor, options]) => {
      const existing = findExistingAgent(vendor, registered);
      if (existing) {
        return { vendor, options, business: existing, source: "registered" as const };
      }
      const business = await autoOnboardSupplier(vendor, options);
      return { vendor, options, business, source: "researched" as const };
    })
  );

  // Reviews + pitches per vendor (parallel).
  const pitched = await Promise.all(
    resolved.map(async (r) => {
      const reviews = await searchReviews(r.business.name);
      const pitch = await vendorPitch(
        r.business,
        r.options,
        itemDescription,
        price,
        reviews
      );
      return { ...r, reviews, pitch };
    })
  );

  // Round 2: the buyer's agent challenges all vendors.
  const challenge = await buyerChallenge(itemDescription, price, pitched);

  // Round 3: each vendor counters the challenge (parallel).
  const counters = await Promise.all(
    pitched.map(async (p) => ({
      vendor: p.business.name,
      content: await vendorCounter(p.business, p.options, challenge, p.reviews),
    }))
  );

  // Judge: rank every concrete option and emit the required structured output.
  const optionsForJudge = pitched
    .flatMap((p) =>
      p.options.map((o) => ({
        supplier_name: p.business.name,
        supplier_location: p.business.location || "",
        item_name: o.item,
        item_description: o.description || "",
        price: o.price,
        currency: o.currency || "SGD",
        order_url: o.order_url || o.link || "",
        agent_source: p.source,
      }))
    );

  const judgeInput = {
    request: { itemDescription, budget: price ?? null },
    pitches: pitched.map((p) => ({ vendor: p.business.name, pitch: p.pitch })),
    challenge,
    counters,
    options: optionsForJudge,
  };

  const judge = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    response_format: { type: "json_object" },
    messages: [
      {
        role: "system",
        content: `You are the buyer's negotiation agent making the final ranking.

You receive: the customer's request, each vendor's pitch, the buyer agent's challenge, each vendor's response to that challenge, and a flat list of concrete options (vendor, item, price, etc.).

Rank the options by how well they satisfy the request, factoring in: relevance to the requested item, price vs budget (penalise over-budget items but still include them), and the persuasiveness/credibility of the vendor pitch.

Return STRICT JSON of this exact shape:
{
  "results": [
    {
      "supplier_name": string,
      "supplier_location": string,
      "total_cost": number,
      "currency": string,
      "item_name": string,
      "item_description": string,
      "score": number (0-100),
      "within_budget": boolean,
      "agent_source": "registered" | "researched",
      "reasoning": string,
      "order_url": string
    }
  ],
  "verdict": "1-2 sentence summary naming the top pick and why."
}
Use ONLY the supplied options — never invent items. "total_cost" is the option price. Order "results" best-first.`,
      },
      { role: "user", content: JSON.stringify(judgeInput) },
    ],
  });

  let results: NegotiatedResult[] = [];
  let verdict = "";
  try {
    const parsed = JSON.parse(judge.choices[0].message.content || "{}");
    results = Array.isArray(parsed.results) ? parsed.results : [];
    verdict = parsed.verdict || "";
  } catch {
    // Fallback: emit unranked options so the caller still gets valid output.
    results = optionsForJudge.map((o) => ({
      supplier_name: o.supplier_name,
      supplier_location: o.supplier_location,
      total_cost: o.price,
      currency: o.currency,
      item_name: o.item_name,
      item_description: o.item_description,
      score: 0,
      within_budget: price == null ? true : o.price <= price,
      agent_source: o.agent_source,
      reasoning: "Ranking unavailable; returning raw options.",
      order_url: o.order_url,
    }));
  }

  return NextResponse.json({
    request: { itemDescription, budget: price ?? null },
    onboarded: resolved
      .filter((r) => r.source === "researched")
      .map((r) => ({ vendor: r.business.name, location: r.business.location })),
    conversation: [
      {
        round: "Initial Pitches",
        entries: pitched.map((p) => ({ speaker: p.business.name, message: p.pitch })),
      },
      {
        round: "Buyer Agent Challenge",
        entries: [{ speaker: "Buyer Agent", message: challenge }],
      },
      {
        round: "Vendor Responses",
        entries: counters.map((c) => ({ speaker: c.vendor, message: c.content })),
      },
    ],
    reviews: pitched.map((p) => ({ vendor: p.business.name, reviews: p.reviews })),
    results,
    verdict,
  });
}
